### ISSUE TITLE
Could not create an instance of type com.android.build.api.component.analytics.AnalyticsEnabledLayered

### ISSUE THREAD

**Issue by CChuYong** [autonomousapps/dependency-analysis-gradle-plugin#1112]
**Build scan link**
[build scan link](https://scans.gradle.com/s/s75ai23ndhy2i)

**Plugin version**
1.29.0

**Gradle version**
8.2

**JDK version**
17.0.2

**(Optional) Kotlin and Kotlin Gradle Plugin (KGP) version**
org.jetbrains.kotlin.android => 1.8.10

**(Optional) Android Gradle Plugin (AGP) version**
com.android.application => 8.2.1

**Describe the bug**
`./gradlew buildHealth` or `./gradlew app:projectHealth` makes same exception
```
> Could not create task ':app:explodeXmlSourceBenchmarkTest'.
   > Could not create an instance of type com.android.build.api.component.analytics.AnalyticsEnabledLayered.
      > Null value provided in parameters [null, id: 3
```

**To Reproduce**
1. ./gradlew buildHealth

**Comment by autonomousapps** [comment]
Thanks for the issue!

**Comment by CChuYong** [comment]
Sure. Here's my same dependency copied version of my project
[Archieve.zip](https://github.com/autonomousapps/dependency-analysis-gradle-plugin/files/14070832/default.zip)

**Comment by mrjano** [comment]
I had this same issue, seems that it works fine on 1.28.0 👍

**Comment by autonomousapps** [comment]
> I had this same issue, seems that it works fine on 1.28.0 👍

Yes, it seems likely this was caused by the migration to the new, non-deprecated AGP APIs in 1.29.0.

**Comment by CChuYong** [comment]
> I had this same issue, seems that it works fine on 1.28.0 👍

This solved my issue of "com.android.build.api.component.analytics.AnalyticsEnabledLayered", but another error "org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunnerKt" has been occured.

For anyone who using jetpack compose with this plugin,
set root kotlin version to 1.9.0 like
```
plugins {
    id("org.jetbrains.kotlin.android") version "1.9.0" apply false
}
```

and set app module's compose compiler version to 1.5.0 (due to kotlin version compatibility) as
```
composeOptions {
    kotlinCompilerExtensionVersion = "1.5.0"
}
```

this solved my issue.

**Comment by autonomousapps** [comment]
I cannot reproduce this issue with the reproducer provided, and the changes suggested in [this comment](https://github.com/autonomousapps/dependency-analysis-gradle-plugin/issues/1112#issuecomment-1935270130). This seems like it might be a Kotlin incompatibility. This plugin currently uses Kotlin 1.9 and is only tested against Kotlin 1.9. Removing from the **next** milestone until I have reason to believe the problem is in this plugin itself.

**Comment by autonomousapps** [comment]
Resolved via https://github.com/autonomousapps/dependency-analysis-gradle-plugin/pull/1132

**Comment by matejdro** [comment]
Still experiencing this with the plugin `1.30.0`

```
Could not determine the dependencies of task ':common-android:synthesizeProjectViewDebug'.
> Could not create task ':common-android:explodeXmlSourceDebug'.
   > Could not create an instance of type com.android.build.api.component.analytics.AnalyticsEnabledLayered.
      > Null value provided in parameters [null, id: 1
        is_debug: true
        minify_enabled: false
        variant_type: LIBRARY
        min_sdk_version {
          api_level: 24
        }
        target_sdk_version {
          api_level: 24
        }
        dex_builder: D8_DEXER
        dex_merger: D8_MERGER
        test_execution: HOST
        ...
```

This is with AGP `8.2.0`, Kotlin `1.9.22` and compose compiler `1.5.9`.

**Comment by autonomousapps** [comment]
Thanks for the repro link. I note your case is not for test sources, but "production" debug sources. I can also see that the library that is failing has no res (and also no source, but this is unrelated). I'm almost certain this is [a bug in AGP itself](https://issuetracker.google.com/issues/325307775), but I think I can workaround it... probably by just try/catching the error 😞
